#!/bin/bash
DOCKER_HOST="dev"
CONTAINER_IP=$1
shift
DISPLAY_IP=$(docker-machine ssh $DOCKER_HOST -t 'who |grep $USER | head -1' | awk '{print $7;}')

docker-machine ssh $DOCKER_HOST -t "slogin -X $CONTAINER_IP env DISPLAY=$DISPLAY_IP:0 $@"
